<?php

use Laravel\Lumen\Testing\DatabaseMigrations;
use Laravel\Lumen\Testing\DatabaseTransactions;

class ChecklistServiceTest extends TestCase
{
    use DatabaseMigrations;
    private $checklistService;

    public function setUp() : void
    {
        parent::setUp();
        $this->checklistService = $this->app->make(\Src\Application\Service\ChecklistService::class);

    }
    public function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

    }

    /**
     * A basic test example.
     *
     * @return void
     */
    public function testGetChecklistNotFound()
    {
        $this->checklistService->getChecklist(1);
        $this->assertFalse(false);
    }

    public function testGetChecklistFound()
    {
        $checklist = factory(\App\Checklist::class)->make();

        $data = $this->checklistService->getChecklist($checklist->id);
        $this->assertNotNull($data);
    }
}
